### ISSUE TITLE
我的问题吗？感觉有些奇怪

### ISSUE THREAD

**Issue by FEI352** [yanhuacuo/98wubi_for_trime#1]
![Screenshot_2024-02-15-21-08-59-061_com drakeet purewriter](https://github.com/yanhuacuo/98wubi_for_trime/assets/104716040/e2600f15-5957-47f4-ac3a-50c372b9c2dd)

**Comment by cppxiaozhu** [comment]
这个表现确实是有问题的，这两天研究一下。

**Comment by cppxiaozhu** [comment]
修好了

**Comment by FEI352** [comment]
> 修好了

确实可以了，有什么办法可以换成横排候选吗？11寸平板16:10的比例，微信QQ这种软件的输出框在底部，逻辑上不适合竖排。
![Screenshot_2024-02-16-00-54-57-549_com drakeet purewriter](https://github.com/yanhuacuo/98wubi_for_trime/assets/104716040/9b5d88e5-0ff0-45b7-87ae-420318667d32)

**Comment by cppxiaozhu** [comment]
> > 修好了
> 
> 确实可以了，有什么办法可以换成横排候选吗？11寸平板16:10的比例，微信QQ这种软件的输出框在底部，逻辑上不适合竖排。 ![Screenshot_2024-02-16-00-54-57-549_com drakeet purewriter](https://private-user-images.githubusercontent.com/104716040/305163537-9b5d88e5-0ff0-45b7-87ae-420318667d32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwNDQ0MzUsIm5iZiI6MTcwODA0NDEzNSwicGF0aCI6Ii8xMDQ3MTYwNDAvMzA1MTYzNTM3LTliNWQ4OGU1LTBmZjAtNDViNy04N2FlLTQyMDMxODY2N2QzMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNlQwMDQyMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NWM2NmViODgwMDA3NzUzMDAzMjM4MDQxZGVhYzUxODZmNTVkODRkY2VhZTk5OTBlZTViYzc4YzhiNjg4YThhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hqqSnmG73xIpN2L31Mb4F7OCyGbURxbR7HCYDR1iEQY)

整个文档，已全部更新。参数，都已做微调，添加了「横向」，带H字眼的专用主题。

**Comment by FEI352** [comment]
> > > 修好了
> > 
> > 
> > 确实可以了，有什么办法可以换成横排候选吗？11寸平板16:10的比例，微信QQ这种软件的输出框在底部，逻辑上不适合竖排。 ![Screenshot_2024-02-16-00-54-57-549_com drakeet purewriter](https://private-user-images.githubusercontent.com/104716040/305163537-9b5d88e5-0ff0-45b7-87ae-420318667d32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwNDQ0MzUsIm5iZiI6MTcwODA0NDEzNSwicGF0aCI6Ii8xMDQ3MTYwNDAvMzA1MTYzNTM3LTliNWQ4OGU1LTBmZjAtNDViNy04N2FlLTQyMDMxODY2N2QzMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNlQwMDQyMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NWM2NmViODgwMDA3NzUzMDAzMjM4MDQxZGVhYzUxODZmNTVkODRkY2VhZTk5OTBlZTViYzc4YzhiNjg4YThhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hqqSnmG73xIpN2L31Mb4F7OCyGbURxbR7HCYDR1iEQY)
> 
> 整个文档，已全部更新。参数，都已做微调，添加了「横向」，带H字眼的专用主题。

![Screenshot_2024-02-16-13-44-31-702_com drakeet purewriter](https://github.com/yanhuacuo/98wubi_for_trime/assets/104716040/641832e4-8a41-41a6-9993-bcf3412a7e0b)
向往能够达到的效果。
![95f7a0d5912331734a3f39fa8d990e44](https://github.com/yanhuacuo/98wubi_for_trime/assets/104716040/f96c56e2-d957-48f8-aac9-f60078f59451)

**Comment by cppxiaozhu** [comment]
对于你期望达到的效果，可以实现编码嵌入：

https://github.com/yanhuacuo/98wubi_for_trime/blob/main/rime/pc_H2.trime.yaml

就是注释掉第 63 行的 composition

其实我们也希望最后的底栏【keys】下的所有东西都隐藏掉，但是同文在这里存在 bug:

https://github.com/osfans/trime/issues/1255

**Comment by yanhuacuo** [comment]
https://github.com/yanhuacuo/98wubi_for_trime/commit/e4b25792142aa68fbbc82304590a76e08554c674
